from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet

import os


def generate_pdf(
    summary,
    medicines,
    diagnosis,
    lab_tests,
    lifestyle,
    comparison=None,
    timeline=None,
    doctor_questions=None,
):

    os.makedirs("reports", exist_ok=True)

    file_path = "reports/AI_Health_Report.pdf"

    styles = getSampleStyleSheet()

    document = SimpleDocTemplate(file_path)

    story = []

    story.append(
        Paragraph("<b>Medical Companion AI Report</b>", styles["Title"])
    )

    story.append(Spacer(1, 20))

    sections = [
        ("Medical Summary", summary),
        ("Medicine Explanation", medicines),
        ("Diagnosis Explanation", diagnosis),
        ("Lab Test Explanation", lab_tests),
        ("Lifestyle Recommendations", lifestyle),
    ]

    if comparison:
        sections.append(("Report Comparison", comparison))

    if timeline:
        sections.append(("Health Timeline", timeline))

    if doctor_questions:
        sections.append(("Questions to Ask Your Doctor", doctor_questions))

    for title, content in sections:

        story.append(
            Paragraph(f"<b>{title}</b>", styles["Heading2"])
        )

        story.append(
            Paragraph(
                content.replace("\n", "<br/>"),
                styles["BodyText"],
            )
        )

        story.append(Spacer(1, 12))

    story.append(
        Paragraph(
            "<b>Disclaimer</b>",
            styles["Heading2"],
        )
    )

    story.append(
        Paragraph(
            "This report is generated by AI for informational purposes only. "
            "It is not a medical diagnosis and should not replace advice from a qualified healthcare professional.",
            styles["BodyText"],
        )
    )

    document.build(story)

    return file_path